server:
  port: 8006


spring:
  application:
    name: consul-payment-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true