server:
  port: 80


spring:
  application:
    name: order-eureka-hystrix-feign

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: defaultZone
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  circuitbreaker:
    enabled: true
