server:
  port: 9527

spring:
  main:
    web-application-type: reactive
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 利用微服务名称进行路由
      routes:
        - id: payment_route #payment route 没有规则，必须唯一
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/*** #路径相匹配的进行路由
            - After=2022-06-01T08:57:05.066+08:00[Asia/Shanghai] #  在这个时间之后可以访问

        - id: payment_route2
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb #路径相匹配的进行路由

        - id: payment_route3
          uri: https://top.baidu.com #匹配后提供服务的路由地址
          predicates:
            - Path=/board #路径相匹配的进行路由

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: defaultZone
    service-url:
      defaultZone: http://localhost:7001/eureka/


