server:
  port: 7001

spring:
  application:
    name: eureka-7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: defaultZone
    service-url:
        defaultZone: http://localhost:7001/eureka/