server:
  port: 80


spring:
  application:
    name: consul-order-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
logging:
    level:
      # feign 日志用什么级别打印接口
      com.cloud.momo.service.PaymentFeignService: info

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50 #单个请求路径的最大连接数
